import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import { GetAllPrefectures } from '../api/axios';
import { Index } from '@/components/Index';

export const getStaticProps = async () => {
  const prefectures = await new GetAllPrefectures().handler();
  return {
    props: {
      prefectures,
    },
  };
};
const Home = ({ prefectures }) => {
  return (
    <>
      <Head>
        <title>人口統計サイト</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Index prefectures={prefectures} />
      </main>
    </>
  );
};

export default Home;
