import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Index } from '@/components/Index';
import { NextPage } from 'next';
import { fetchPrefectureList } from '@/hooks/prefectureListHooks';
import { Prefecture } from '@/types/types';

type HomeProps = {
  prefectureList: Prefecture[];
};

export const getStaticProps = async () => {
  const prefectureList = await fetchPrefectureList();

  return {
    props: {
      prefectureList,
    },
  };
};
const Home: NextPage<HomeProps> = ({ prefectureList }) => {
  return (
    <>
      <Head>
        <title>人口統計サイト</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Index prefectureList={prefectureList} />
      </main>
    </>
  );
};

export default Home;
